/**
 * 
 */
package it.polimi.deib.provaFinale2014.andrea.celli_stefano1.cereda.server;

import it.polimi.deib.provaFinale2014.andrea.celli_stefano1.cereda.gameController.server.GameController;
import it.polimi.deib.provaFinale2014.andrea.celli_stefano1.cereda.gameModel.players.Player;

/**
 * This class is used to represent a disconnected client, it is represented by
 * the id of the client and a reference to the player controlled and to the game
 * played. Two disconnected clients are equals if they have the same id
 * 
 * @author Stefano
 * 
 */
public class DisconnectedClient {
	/** The id of the client */
	private int clientID;
	/** The controlled player */
	private Player controlledPlayer;
	/** The game manager associated to the client */
	private GameController game;

	/**
	 * The constructor saves the parameter
	 * 
	 * @param clientID
	 *            The id of the client
	 * @param controlledPlayer
	 *            The controlled player
	 * @param game
	 *            The game manager associated to the client
	 */
	public DisconnectedClient(int clientID, Player controlledPlayer,
			GameController game) {
		this.clientID = clientID;
		this.controlledPlayer = controlledPlayer;
		this.game = game;
	}

	/**
	 * @return the clientID
	 */
	public int getClientID() {
		return clientID;
	}

	/**
	 * @return the controlledPlayer
	 */
	public Player getControlledPlayer() {
		return controlledPlayer;
	}

	/**
	 * @return the game
	 */
	public GameController getGame() {
		return game;
	}

	/**
	 * This hashCode has been automatically generated by Eclipse, it's based
	 * only on the id
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + clientID;
		return result;
	}

	/**
	 * This equals has been automatically generated by Eclipse, it's based only
	 * on the id
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof DisconnectedClient)) {
			return false;
		}
		DisconnectedClient other = (DisconnectedClient) obj;
		if (clientID != other.clientID) {
			return false;
		}
		return true;
	}

}
