package it.polimi.deib.provaFinale2014.andrea.celli_stefano1.cereda.client.interfaces.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

/**
 * This class manages the selection of a new card. It handles the action events
 * generated by the buttons. It also adds and remove the buy card panel.
 * 
 * @author Andrea
 * 
 */

public class BuyCardManager implements ActionListener {

	/**
	 * The map on which the buy card panel will be displayed
	 */
	private GameMap gameMap;

	/** Used to send moves back and to get information on adjacent terrains */
	private InterfaceGui interfaceGui;

	/** The displayed panel */
	BuyCardPanel buyCardPanel;

	public BuyCardManager(GameMap map, InterfaceGui interfaceGui) {
		gameMap = map;
		this.interfaceGui = interfaceGui;
	}

	/**
	 * This method creates a new buy card panel displaying the available cards
	 */
	public void getNewCard() {

		ArrayList buyable = (ArrayList) interfaceGui
				.getGameController()
				.getBoardStatus()
				.getCardsPlayerCanBuy(
						interfaceGui.getGameController().getControlledPlayer());

		buyCardPanel = new BuyCardPanel(buyable, this);
		gameMap.add(buyCardPanel);
		buyCardPanel.setSize(gameMap.getWidth() / 3, gameMap.getHeight() / 3);
		buyCardPanel.setLocation(gameMap.getWidth() / 3,
				gameMap.getHeight() / 3);
		buyCardPanel.setVisible(true);

	}

	/** This method removes the buy card panel */
	public void removeBuyCardPanel() {

	}

	/** This is the listener which is called when a button is pressed */
	public void actionPerformed(ActionEvent e) {
	}

}
